<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<?php
        // 定义数组
        $carList = array();
        // 往数组中添加数据
        $carList[]=array("path"=>"img/33.jpg","name"=>"奥迪");
        $carList[]=array("path"=>"img/35.jpg","name"=>"阿斯顿·马丁");
        $carList[]=array("path"=>"img/221.jpg","name"=>"安凯客车");
        $carList[]=array("path"=>"img/117.jpg","name"=>"AC Schnitzer");
        $carList[]=array("path"=>"img/276.jpg","name"=>"ALPINA");
        $carList[]=array("path"=>"img/34.jpg","name"=>"阿尔法·罗密欧");
        $carList[]=array("path"=>"img/36.jpg","name"=>"奔驰");
        $carList[]=array("path"=>"img/14.jpg","name"=>"本田");
        $carList[]=array("path"=>"img/38.jpg","name"=>"别克");
        $carList[]=array("path"=>"img/15.jpg","name"=>"宝马");
        $carList[]=array("path"=>"img/75.jpg","name"=>"比亚迪");
        $carList[]=array("path"=>"img/120.jpg","name"=>"宝骏");
        $carList[]=array("path"=>"img/13.jpg","name"=>"标致");
        $carList[]=array("path"=>"img/40.jpg","name"=>"保时捷");
        $carList[]=array("path"=>"img/203.jpg","name"=>"北汽幻速");
        $carList[]=array("path"=>"img/27.jpg","name"=>"北京");
        $carList[]=array("path"=>"img/173.jpg","name"=>"北汽绅宝");
        $carList[]=array("path"=>"img/231.jpg","name"=>"宝沃");
        $carList[]=array("path"=>"img/154.jpg","name"=>"北汽制造");
        $carList[]=array("path"=>"img/39.jpg","name"=>"宾利");
        $carList[]=array("path"=>"img/143.jpg","name"=>"北汽威旺");
        $carList[]=array("path"=>"img/95.jpg","name"=>"奔腾");
        $carList[]=array("path"=>"img/208.jpg","name"=>"北汽新能源");
        $carList[]=array("path"=>"img/140.jpg","name"=>"巴博斯");
        $carList[]=array("path"=>"img/271.jpg","name"=>"比速汽车");
        $carList[]=array("path"=>"img/37.jpg","name"=>"布加迪");
        $carList[]=array("path"=>"img/301.jpg","name"=>"北汽道达");
        $carList[]=array("path"=>"img/76.jpg","name"=>"长安");
        $carList[]=array("path"=>"img/77.jpg","name"=>"长城");
        $carList[]=array("path"=>"img/163.jpg","name"=>"长安欧尚");
        $carList[]=array("path"=>"img/79.jpg","name"=>"昌河");
        $carList[]=array("path"=>"img/196.jpg","name"=>"成功汽车");
        $carList[]=array("path"=>"img/294.jpg","name"=>"长安轻型车");
        $carList[]=array("path"=>"img/299.jpg","name"=>"长安跨越");
        $carList[]=array("path"=>"img/1.jpg","name"=>"大众");
        $carList[]=array("path"=>"img/113.jpg","name"=>"东风风神");
        $carList[]=array("path"=>"img/169.jpg","name"=>"DS");
        $carList[]=array("path"=>"img/259.jpg","name"=>"东风风光");
        $carList[]=array("path"=>"img/81.jpg","name"=>"东南");
        $carList[]=array("path"=>"img/165.jpg","name"=>"东风风行");
        $carList[]=array("path"=>"img/32.jpg","name"=>"东风");
        $carList[]=array("path"=>"img/41.jpg","name"=>"道奇");
        $carList[]=array("path"=>"img/187.jpg","name"=>"东风风度");
        $carList[]=array("path"=>"img/142.jpg","name"=>"东风小康");
        $carList[]=array("path"=>"img/3.jpg","name"=>"丰田");
        $carList[]=array("path"=>"img/8.jpg","name"=>"福特");
        $carList[]=array("path"=>"img/197.jpg","name"=>"福汽启腾");
        $carList[]=array("path"=>"img/11.jpg","name"=>"菲亚特");
        $carList[]=array("path"=>"img/96.jpg","name"=>"福田");
        $carList[]=array("path"=>"img/42.jpg","name"=>"法拉利");
        $carList[]=array("path"=>"img/141.jpg","name"=>"福迪");
        $carList[]=array("path"=>"img/282.jpg","name"=>"福田乘用车");
        $carList[]=array("path"=>"img/82.jpg","name"=>"广汽传祺");
        $carList[]=array("path"=>"img/152.jpg","name"=>"观致");
        $carList[]=array("path"=>"img/108.jpg","name"=>"广汽吉奥");
        $carList[]=array("path"=>"img/112.jpg","name"=>"GMC");
        $carList[]=array("path"=>"img/116.jpg","name"=>"光冈");
        $carList[]=array("path"=>"img/181.jpg","name"=>"哈弗");
        $carList[]=array("path"=>"img/86.jpg","name"=>"海马");
        $carList[]=array("path"=>"img/91.jpg","name"=>"红旗");
        $carList[]=array("path"=>"img/97.jpg","name"=>"黄海");
        $carList[]=array("path"=>"img/260.jpg","name"=>"华泰新能源");
        $carList[]=array("path"=>"img/150.jpg","name"=>"海格");
        $carList[]=array("path"=>"img/87.jpg","name"=>"华泰");
        $carList[]=array("path"=>"img/24.jpg","name"=>"哈飞");
        $carList[]=array("path"=>"img/164.jpg","name"=>"恒天");
        $carList[]=array("path"=>"img/220.jpg","name"=>"华颂");
        $carList[]=array("path"=>"img/245.jpg","name"=>"华凯");
        $carList[]=array("path"=>"img/267.jpg","name"=>"汉腾汽车");
        $carList[]=array("path"=>"img/43.jpg","name"=>"悍马");
        $carList[]=array("path"=>"img/85.jpg","name"=>"华普");
        $carList[]=array("path"=>"img/237.jpg","name"=>"华利");
        $carList[]=array("path"=>"img/25.jpg","name"=>"吉利汽车");
        $carList[]=array("path"=>"img/46.jpg","name"=>"Jeep");
        $carList[]=array("path"=>"img/84.jpg","name"=>"江淮");
        $carList[]=array("path"=>"img/44.jpg","name"=>"捷豹");
        $carList[]=array("path"=>"img/83.jpg","name"=>"金杯");
        $carList[]=array("path"=>"img/119.jpg","name"=>"江铃");
        $carList[]=array("path"=>"img/175.jpg","name"=>"金旅");
        $carList[]=array("path"=>"img/270.jpg","name"=>"江铃集团新能源");
        $carList[]=array("path"=>"img/151.jpg","name"=>"九龙");
        $carList[]=array("path"=>"img/210.jpg","name"=>"江铃集团轻汽");
        $carList[]=array("path"=>"img/145.jpg","name"=>"金龙");
        $carList[]=array("path"=>"img/47.jpg","name"=>"凯迪拉克");
        $carList[]=array("path"=>"img/214.jpg","name"=>"凯翼");
        $carList[]=array("path"=>"img/101.jpg","name"=>"开瑞");
        $carList[]=array("path"=>"img/9.jpg","name"=>"克莱斯勒");
        $carList[]=array("path"=>"img/199.jpg","name"=>"卡威");
        $carList[]=array("path"=>"img/224.jpg","name"=>"卡升");
        $carList[]=array("path"=>"img/219.jpg","name"=>"康迪全球鹰");
        $carList[]=array("path"=>"img/109.jpg","name"=>"KTM");
        $carList[]=array("path"=>"img/100.jpg","name"=>"科尼赛克");
        $carList[]=array("path"=>"img/156.jpg","name"=>"卡尔森");
        $carList[]=array("path"=>"img/49.jpg","name"=>"路虎");
        $carList[]=array("path"=>"img/52.jpg","name"=>"雷克萨斯");
        $carList[]=array("path"=>"img/53.jpg","name"=>"铃木");
        $carList[]=array("path"=>"img/78.jpg","name"=>"猎豹汽车");
        $carList[]=array("path"=>"img/51.jpg","name"=>"林肯");
        $carList[]=array("path"=>"img/10.jpg","name"=>"雷诺");
        $carList[]=array("path"=>"img/88.jpg","name"=>"陆风");
        $carList[]=array("path"=>"img/80.jpg","name"=>"力帆汽车");
        $carList[]=array("path"=>"img/54.jpg","name"=>"劳斯莱斯");
        $carList[]=array("path"=>"img/124.jpg","name"=>"理念");
        $carList[]=array("path"=>"img/48.jpg","name"=>"兰博基尼");
        $carList[]=array("path"=>"img/50.jpg","name"=>"路特斯");
        $carList[]=array("path"=>"img/241.jpg","name"=>"LOCAL MOTORS");
        $carList[]=array("path"=>"img/204.jpg","name"=>"陆地方舟");
        $carList[]=array("path"=>"img/118.jpg","name"=>"Lorinser");
        $carList[]=array("path"=>"img/89.jpg","name"=>"莲花汽车");
        $carList[]=array("path"=>"img/58.jpg","name"=>"马自达");
        $carList[]=array("path"=>"img/20.jpg","name"=>"名爵");
        $carList[]=array("path"=>"img/57.jpg","name"=>"玛莎拉蒂");
        $carList[]=array("path"=>"img/168.jpg","name"=>"摩根");
        $carList[]=array("path"=>"img/56.jpg","name"=>"MINI");
        $carList[]=array("path"=>"img/129.jpg","name"=>"迈凯伦");
        $carList[]=array("path"=>"img/55.jpg","name"=>"迈巴赫");
        $carList[]=array("path"=>"img/130.jpg","name"=>"纳智捷");
        $carList[]=array("path"=>"img/213.jpg","name"=>"南京金龙");
        $carList[]=array("path"=>"img/60.jpg","name"=>"讴歌");
        $carList[]=array("path"=>"img/146.jpg","name"=>"欧朗");
        $carList[]=array("path"=>"img/59.jpg","name"=>"欧宝");
        $carList[]=array("path"=>"img/61.jpg","name"=>"帕加尼");
        $carList[]=array("path"=>"img/62.jpg","name"=>"起亚");
        $carList[]=array("path"=>"img/26.jpg","name"=>"奇瑞");
        $carList[]=array("path"=>"img/122.jpg","name"=>"启辰");
        $carList[]=array("path"=>"img/235.jpg","name"=>"前途");
        $carList[]=array("path"=>"img/63.jpg","name"=>"日产");
        $carList[]=array("path"=>"img/19.jpg","name"=>"荣威");
        $carList[]=array("path"=>"img/174.jpg","name"=>"如虎");
        $carList[]=array("path"=>"img/296.jpg","name"=>"瑞驰新能源");
        $carList[]=array("path"=>"img/103.jpg","name"=>"瑞麒");
        $carList[]=array("path"=>"img/68.jpg","name"=>"三菱");
        $carList[]=array("path"=>"img/67.jpg","name"=>"斯柯达");
        $carList[]=array("path"=>"img/65.jpg","name"=>"斯巴鲁");
        $carList[]=array("path"=>"img/155.jpg","name"=>"上汽大通");
        $carList[]=array("path"=>"img/69.jpg","name"=>"双龙");
        $carList[]=array("path"=>"img/205.jpg","name"=>"赛麟");
        $carList[]=array("path"=>"img/45.jpg","name"=>"smart");
        $carList[]=array("path"=>"img/149.jpg","name"=>"陕汽通家");
        $carList[]=array("path"=>"img/238.jpg","name"=>"斯达泰克");
        $carList[]=array("path"=>"img/162.jpg","name"=>"思铭");
        $carList[]=array("path"=>"img/269.jpg","name"=>"SWM斯威汽车");
        $carList[]=array("path"=>"img/66.jpg","name"=>"世爵");
        $carList[]=array("path"=>"img/90.jpg","name"=>"双环");
        $carList[]=array("path"=>"img/133.jpg","name"=>"特斯拉");
        $carList[]=array("path"=>"img/202.jpg","name"=>"泰卡特");
        $carList[]=array("path"=>"img/161.jpg","name"=>"腾势");
        $carList[]=array("path"=>"img/70.jpg","name"=>"沃尔沃");
        $carList[]=array("path"=>"img/114.jpg","name"=>"五菱汽车");
        $carList[]=array("path"=>"img/167.jpg","name"=>"五十铃");
        $carList[]=array("path"=>"img/283.jpg","name"=>"WEY");
        $carList[]=array("path"=>"img/192.jpg","name"=>"潍柴英致");
        $carList[]=array("path"=>"img/99.jpg","name"=>"威兹曼");
        $carList[]=array("path"=>"img/284.jpg","name"=>"蔚来");
        $carList[]=array("path"=>"img/102.jpg","name"=>"威麟");
        $carList[]=array("path"=>"img/71.jpg","name"=>"雪佛兰");
        $carList[]=array("path"=>"img/12.jpg","name"=>"现代");
        $carList[]=array("path"=>"img/72.jpg","name"=>"雪铁龙");
        $carList[]=array("path"=>"img/185.jpg","name"=>"新凯");
        $carList[]=array("path"=>"img/98.jpg","name"=>"西雅特");
        $carList[]=array("path"=>"img/73.jpg","name"=>"英菲尼迪");
        $carList[]=array("path"=>"img/110.jpg","name"=>"一汽");
        $carList[]=array("path"=>"img/144.jpg","name"=>"依维柯");
        $carList[]=array("path"=>"img/111.jpg","name"=>"野马汽车");
        $carList[]=array("path"=>"img/263.jpg","name"=>"驭胜");
        $carList[]=array("path"=>"img/298.jpg","name"=>"宇通客车");
        $carList[]=array("path"=>"img/93.jpg","name"=>"永源");
        $carList[]=array("path"=>"img/232.jpg","name"=>"御捷");
        $carList[]=array("path"=>"img/94.jpg","name"=>"众泰");
        $carList[]=array("path"=>"img/22.jpg","name"=>"中华");
        $carList[]=array("path"=>"img/74.jpg","name"=>"中兴");
        $carList[]=array("path"=>"img/182.jpg","name"=>"之诺");
        $carList[]=array("path"=>"img/206.jpg","name"=>"知豆");

        for($i=0;$i<count($carList);$i++){
    ?>

    <li><img src="<?php echo $carList[$i]['path']?>" alt="">---<span><?php echo $carList[$i]['name'] ?></span></li>
    <?php } ?>
</body>
</html>